for_window [class="^.*"] border pixel 2 
default_border pixel 2
default_floating_border pixel 2

# configure spaces between windows & screen
gaps inner 5px
gaps outer 3px

# border
#default_border pixel 2
hide_edge_borders smart 

# fonts
font pango:JetBrainsMono Nerd Font 12

# Monokai Pro Color scheme setup
# class                 border  backgr. text    indicator child_border
client.focused          #78DCE8 #78DCE8 #2D2A2E #AB9DF2   #78DCE8
client.focused_inactive #403E41 #403E41 #FCFCFA #403E41   #403E41
client.unfocused        #2D2A2E #2D2A2E #7D7D7D #2D2A2E   #2D2A2E
client.urgent           #FF6188 #FF6188 #FCFCFA #FF6188   #FF6188
client.placeholder      #2D2A2E #0C0C0C #FCFCFA #2D2A2E   #0C0C0C
client.background       #2D2A2E

# set floating window size
for_window [class="feh"] floating enable
for_window [class="thunar"] floating enable
for_window [class="blueman-manager"] floating enable, sticky enable
for_window [class="qbittorent"] floating enable
