#!/usr/bin/env bash

# NOTE: pamixer is no longer maintained. fork and maintain it yourself:)
dir="$HOME/.config/qtile/icons/notifications/"

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i ${dir}/"volume-$1".png "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer --unmute
	pamixer -i 5 --allow-boost
	send_notification $1
	;;
down)
	pamixer --unmute
    pamixer -d 5
	send_notification $1
	;;
mute)
	pamixer --toggle-mute
	if $(pamixer --get-mute); then
		dunstify -i ${dir}/volume-mute.png -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
