#!/bin/bash

dir="$HOME/.config/qtile/icons/notifications/"

function send_notification() {
    brightness=$(brightnessctl get)
    max_brightness=$(brightnessctl max)
    # Calculate brightness percentage
    percent=$(( 100 * brightness / max_brightness ))
    dunstify -a "changebrightness" -u low -r "9994" -h int:value:"$percent" -i ${dir}/"brightness-$1".png "Brightness: ${percent}%" -t 2000
}

case $1 in
up)
    brightnessctl set +5%
    send_notification
    ;;
down)
    brightnessctl set 5%-
    send_notification
    ;;
esac
