[ids]

*
                                                                                    
[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

# Enables the keys for the next press only
# you do not have to hold them down
shift = oneshot(shift)

# vim.like keys globally
# [alt]
# h = left
# j = down
# k = up
# l = right
#
# u = pageup
# d = pagedown

