#!/usr/bin/env bash

set -eou pipefail

# FIXME:
# cannot read external devices: hardisks, usbs, phones and such
# bluetooth was impossible to setup correctly
# screen sleeps even when watching things, on mpv or browser?!

# --- VARIABLES --- #

LANG_PACKAGES=(
    perl lua python LuaJIT make gcc clang nodejs git git-lfs stow keyd
    docker docker-buildx docker-compose base-devel libffi-devel
    bzip2-devel openssl openssl-devel readline
    python3-pipx python3-psutil python3-dbus-fast python3-xcffib
    # packages not in default void
    psmisc tree bash-completion
)
USERLAND_PACKAGES=(
    qtile xfce4 bash btop alacritty cmus gnome-themes-extra flameshot
    vim neovim tmux alacritty noto-fonts-emoji noto-fonts-ttf noto-fonts-cjk
    qbittorrent gparted wget curl bluez libspa-bluetooth xclip
    mariadb sublime-merge void-repo-nonfree pipewire ripgrep alsa-pipewire
    zathura zathura-pdf-poppler zathura-pdf-mupdf zathura-ps zathura-ps zathura-cb zathura-djvu
    polkit picom NetworkManager network-manager-applet rtkit blueman
    rofi dunst feh mpv brightnessctl redshift redshift-gtk btop ImageMagick
    unzip autoconf automake xset xrandr ffmpeg
)
TEMP_DIR=$(mktemp -d)

# --- FUNCTIONS --- #

usage() {
    echo "
    Install system confiuration files and programs instantly.

    Usage: $ $0 [OPTIONS]

    A list of options is listed below:

    -b, --base              install system packages and configurations
    -d, --dots              clone dotfiles and set them up
    -s, --services          symlink essential startup daemons
    -h, ---help             print this help segment and exit
    "
}

cleanup() {
    # remove temp_dir created in a particular section
    rm -rf "$TEMP_DIR"
}

install_fonts() {
    local fonts_dir="$HOME/.local/share/fonts"
    if [[ ! -d "$fonts_dir" ]]; then 
        mkdir -p "$fonts_dir"
    fi

    cd $TEMP_DIR
    wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.zip
    wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip

    unzip FiraMono.zip -d "$fonts_dir"
    unzip JetBrainsMono.zip -d "$fonts_dir"
    fc-cache -fv
}

setup_audio() {
    sudo xbps-install pipewire alsa-pipewire wireplumber

    ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
    ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/

    # enable pipewire and pipewire-pulse autostart
    if [ -e "/usr/share/applications/pipewire.desktop" ] && [ -e "/etc/xdg/autostart/" ]; then
        ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/pipewire.desktop
        ln -s /usr/share/applications/pipewire-pulse.desktop /etc/xdg/autostart/pipewire-pulse.desktop
    fi

    # alsa configuration
    ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
    ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
}

setup_dots() {
    local DOTS_DIR="~/.dotfiles"
    local DOTS_BACKUP="~/.dotfiles.backup"
    local TARGET_BRANCH="xorg/void"

    git clone ssh://git@github.com/mbvgua/dotfiles.git "$DOTS_DIR"
    cd "$DOTS_DIR"

    # pull all remote branches locally
    git !git branch -r | \
        grep -v "\->" | \
        while read remote; do \
            git branch --track "${remote#origin/}" "$remote"; \
        done && \
        git fetch --all && \
        git pull --all

    git checkout "$TARGET_BRANCH"
    stow .
}

startup_services() {
    local services=(
        # bluetoothd bluetooth
        lightdm elogind NetworkManager containerd dbus docker mysqld keyd polkitd
    )

    for service in "${services[@]}"; do
        if [[ ! -d "/etc/sv/$service" ]]; then
            echo "$service not found in /etc/sv directory..."
            echo "aborting operation"
            echo "please install: $service"
            exit 1
        fi

        # If present, symlink...
        # FIX: it would be better to first recursively go through loop above
        # then if all are present,now do this. if some are absent, add to a
        # not_found array, then present list to user
        sudo ln -s /etc/sv/"$service" /var/service
    done
}

# --- IMPLEMENTATION --- #

# when script exits, remove the temp dir created
trap cleanup EXIT

if [[ "$#" -eq 1 ]]; then 

    OPERATION="$1"

    case $OPERATION in
        "--base" | "-b" )
            echo "1.) installing base packages..."
            sudo xbps-install -Syu "${LANG_PACKAGES[@]}" "${USERLAND_PACKAGES[@]}"

            echo "2.) installing system fonts..."
            install_fonts

            echo "3.) setting up audio..."
            setup_audio

            # touchpad click support
            echo "4.) adding touchpad click support..."
            sudo cp ./40-libinput-touchpad.conf /etc/X11/xorg.conf.d/

            # remapping keyboard keys with keyd
            echo "5.) remapping keyboard layout..."
            sudo cp ./default.conf /etc/keyd/

            # install misc packages
            echo "6.) Misc setup..."
            sudo npm install -g typescript
            pipx install git-filter-repo yt-dlp fastapi
            ;;
        "--dots" | "-d")
            echo "Configuring dotfiles..."
            if [[ ! -d "$DOTS_DIR" ]]; then
                echo "seting up your dotfiles..."
                setup_dots
            else
                echo "$DOTS_DIR directory found, safely moving it to $DOTS_BACKUP"
                mv -r "$DOTS_DIR" "$DOTS_BACKUP"
                echo "seting up your dotfiles..."
                setup_dots
            fi
            ;;
        "--services" | "-s")
            echo "Configure system services to launch on startup..."
            startup_services
            ;;
        "--help" | "-h")
            usage
            exit 1
            ;;
        *)
            echo "Unkown option $OPERATION"
            echo "Use --help for usage information"
            exit 1
    esac
elif [[ "$#" -eq 0 ]]; then
    echo "No arguments passed"
    usage
    exit 2
else
    echo "Too many arguments passed"
    usage
    exit 2
fi

