#!/usr/bin/env bash

tools=(
    # cpp deepin-screenshot
    "perl lua python LuaJIT make gcc clang nodejs pnpm git git-lfs stow keyd"
    "wget curl bluez libspa-bluetooth lxappearance qbittorrent scrot"
    "qtile bash tmux neovim vim btop alacritty cmus mariadb nerd-fonts"
    "docker docker-buildx docker-compose btop void-repo-nonfree gnome-themes-extra"
    "zathura zathura-pdf-poppler zathura-pdf-mupdf zathura-ps zathura-ps zathura-cb zathura-djvu"
    "rofi dunst feh mpv brightnessctl redshift redshift-gtk pipewire ripgrep alsa-pipewire"
    "polkit xfce4 picom NetworkManager network-manager-applet rtkit blueman"
    "unzip autoconf automake xset xrandr ffmpeg ImageMagick gparted udiskie udisks2"
    "python3-pipx python3-psutil python3-dbus-fast python3-xcffib xclip"
    "base-devel libffi-devel bzip2-devel openssl openssl-devel readline readline-devel sqlite-devel xz liblzma-devel zlib zlib-devel libzstd-devel"     #build deps for pyenv
)


pkg_manager="xbps-query"

install_base(){
    sudo ${pkg_manager} ${tools[@]}
}

# post_install(){
#     KEYD
#     add keyd config
#
#     STOW
#     add stow symlinks
#
#     CARGO
#     install tree-sitter
#
#     PNPM
#     install typescript globally
#     diff-so-fancy globally
#
#     HELIUM
#     pull helium appimage
#     move to home directory
#     make it executable
#
#     PYTHON
#     pip install pipx
#     pipx install "fastapi[standard]"
#
#     TTY
#     change default font size for tty
#
#     DOCKER
#     enable docker engine on every bootup
#     pull mysql docker image
#     pull postgres docker image
#
#     SUBlIME MERGE
#     install sublime merge. work with git visual alias
# }

install_base
