#!/usr/bin/env bash

tools=(
    # dev tools
    "cpp perl lua python luajit make gcc clang"
    "git git-lfs diff-so-fancy stow keyd wget curl"
    "bash tmux nvim vim btop wezterm cmus"
    "docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
    # wm_tools
    "mpv zathura zathura-pdf-poppler zathura-pdf-mupdf zathura-ps zathura-ps zathura-cb zathura-djvu"
    "deepin-screenshot rofi dunst feh picom polkit brightnessctl redshift unzip"
    "network-manager-applet pulsemixer paplay pipewire-pulse"
    "lxappearance Thunar xfce4-power-manager xfce4-screensaver ImageMagick"
    "autoconf automake libXinerama libXrandr pkgconf xset xrandr"
    "cairo-devel libev-devel libjpeg-turbo-devel libxkbcommon-devel libxkbcommon-x11-devel"
    "libXrandr-devel imlib2-devel pam-devel xcb-util-image-devel xcb-util-xrm-devel"
)


pkg_manager="dnf"

install_base(){
    sudo ${pkg_manager} install -y ${tools[@]}
}

# post_install(){
#     KEYD
#     add keyd config
#
#     STOW
#     add stow symlinks
#
#     HELIUM
#     pull helium appimage
#     move to home directory
#     make it executable
#
#     WEZTERM
#     install wezterm via copr
#
#     PYTHON
#     pip install pipx
#     pipx install poetry "fastapi[standard]"
#
#     TTY
#     change default font size for tty
#
#     DOCKER
#     enable docker engine on every bootup
#     pull mysql docker image
#     pull postgres docker image
#
#     SUBlIME MERGE
#     install sublime merge. work with git visual alias
# }

install_base
