#+Title: emacs configuration
#+Author: mbugua
#+Description: minimal emacs config to get you started
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents :toc:
- [[#introduction][Introduction]]
  - [[#what-is-kickstartemacs][What is Kickstart.emacs?]]
  - [[#ctrl--meta][Ctrl & Meta]]
  - [[#where-to-start][Where to start?]]
  - [[#getting-help][Getting Help]]
- [[#core-setup--performance][Core Setup & Performance]]
  - [[#startup-performance][Startup Performance]]
  - [[#auto-tangle-configuration-file][Auto-tangle Configuration file]]
  - [[#show-startup-time][Show startup time]]
  - [[#package-manager][Package manager]]
  - [[#good-defaults][Good Defaults]]
  - [[#dired][Dired]]
- [[#important-to-load-first][Important to load first]]
  - [[#evil-mode][Evil Mode]]
  - [[#general-keybindings][General Keybindings]]
  - [[#undo][Undo]]
- [[#appearance][Appearance]]
  - [[#set-theme][Set Theme]]
  - [[#doom-modeline][Doom Modeline]]
  - [[#nerd-icons][Nerd Icons]]
- [[#development][Development]]
  - [[#eglot][Eglot]]
  - [[#masonel][Mason.el]]
  - [[#sideline-flymake][Sideline-flymake]]
  - [[#yasnippet][Yasnippet]]
  - [[#tree-sitter][Tree-Sitter]]
  - [[#language-modes][Language modes]]
  - [[#shells][Shells]]
  - [[#sudo-edit][Sudo Edit]]
  - [[#dotenv][Dotenv]]
- [[#multi-file-example][Multi File Example]]
  - [[#adding-the-lisp-directory-to-load-path][Adding the lisp directory to load-path]]
  - [[#sourcing-the-files][Sourcing the files]]
  - [[#using-the-file][Using the file]]
- [[#version-control][Version Control]]
  - [[#magit][Magit]]
  - [[#diff-hl][Diff-hl]]
- [[#completion][Completion]]
  - [[#corfu][Corfu]]
  - [[#cape][Cape]]
  - [[#orderless][Orderless]]
  - [[#vertico-and-marginalia][Vertico and Marginalia]]
  - [[#jinx][Jinx]]
- [[#other-packages][Other packages]]
  - [[#consult][Consult]]
  - [[#helpful][Helpful]]
  - [[#diminish][Diminish]]
  - [[#rainbow-delimiters][Rainbow Delimiters]]
  - [[#rainbow-mode][Rainbow Mode]]
  - [[#hl-todo][Hl-todo]]
  - [[#indent-guide][Indent-guide]]
  - [[#which-key][Which-Key]]
  - [[#ws-butler][Ws-butler]]

* Introduction
#+begin_src emacs-lisp :tangle no
    ;;==================================================================;;
    ;;================== READ THIS BEFORE CONTINUING ===================;;
    ;;==================================================================;;
    ;;======                                    .-----.          =======;;
    ;;======         .----------------------.   | === |          =======;;
    ;;======         |.-""""""""""""""""""-.|   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         ||  'KICKSTART.EMACS' ||   |-----|          =======;;
    ;;======         ||                    ||   | === |          =======;;
    ;;======         || M-X:               ||   |-----|          =======;;
    ;;======         || help-with-tutorial ||   |:::::|          =======;;
    ;;======         |'-..................-'|   |____o|          =======;;
    ;;======         `"")----------------(""`   ____________     =======;;
    ;;======        /::::::::::|  |:::::p::::\  \ Only CTRL \    =======;;
    ;;======       /:::=======f|  |========:::\  \ required  \   =======;;
    ;;======      'CTRL""""""""'  'bn""""""""""'  '""""""""""'   =======;;
    ;;======                                                     =======;;
    ;;==================================================================;;
    ;;==================================================================;;
#+end_src

** What is Kickstart.emacs?
Kickstart.emacs is *not* a distribution.
It's a template for your own configuration.
Inspired by kickstart.nvim.

It is *recommended* to configure it from the *init.org* file.

Kickstart.emacs is a starting point for your own configuration.
The goal is that you read every line, top-to-bottom, understand
what your configuration is doing, and modify it to suit your needs.

After you've done that, you can start making your own configuration out of this
or taking the things you like and making something new from scratch.
The choice is yours. You can do basically anything with Emacs.
So don't hesitate to try things out.

You can delete this when you're done. It's your config now. :)
I hope you have fun with your Emacs journey.
MiniApollo

** Ctrl & Meta
This is from the Emacs tutorial, but I put this here for safety.

Emacs commands generally involve the CONTROL key (often labeled CTRL)
or the META key (usually labeled ALT). Rather than writing that
in full each time, we'll use the following abbreviations:

C-<chr>  means hold the CONTROL key while typing the character <chr>.
Thus, C-f would be: hold the CONTROL key and type f.
M-<chr>  means hold the META or ALT key down while typing <chr>.
If there is no META or ALT key, instead press and release the
ESC key and then type <chr>.  We write <ESC> for the ESC key.

** Where to start?
First I recommend starting with the Emacs tutorial with the following keybinding: C-h t
Or running the command with M-x: help-with-tutorial
Even if you plan on using Vim keybindings later on, it's a good idea to learn the standard Emacs keybindings.
If you already know the standard Emacs keybindings, you can skip this step.

After you completed that, you should start learning Emacs lisp.
It is not necessary to know elisp, but I recommend it. It will open up a whole new world, trust me.
I used Emacs and Neovim without knowing much about the core language and just copy pasting packages or plugins.
But after learning the fundamentals you can customize basically anything and I really mean ANYTHING.

This will look daunting at first, but don't be scared. This is why I am here.
Elisp is not harder than lua or any other language.

If you don't know anything about elisp, I recommend taking some time to read through
a guide. One possible example which will only take 10-15 minutes:
https://learnxinyminutes.com/elisp/

Or if you want to know everything about elisp:
https://www.gnu.org/software/emacs/manual/html_node/eintr/

** Getting Help
If you get stuck or confused about something, you're in luck:
Because Emacs has a really good help functionality.
Everything under C-h is used for help keybindings.

Using the following keybind: C-h C-h
Or running the following command M-x: help-for-help
Will open up the Emacs help for help menu (I know it's a really creative name :D).
This is the central place where you can see all possible commands you can use when you are stuck.

The most used commands for me are:
- C-h v Describe variable
- C-h f Describe function
- C-h k Describe key

Other also really useful ones:
- C-h i Show all installed manuals
- C-h r Emacs manual
- C-h a Search for commands (see also M-x: Apropos)
- C-h m Show help for current major and minor modes

These commands should be the first thing you use when you're stuck or confused with something.

*** Searching the manual
The manual has a specific mode called info-mode.
Which has useful features you can use.
For more about info-mode: C-h f: info-mode

Basic navigation:
- d key: Go back to the top-level Info Directory.
- u key: Go up to the parent node in the document's hierarchy.
- n key: for next node in the current manual.
- p key: for previous node in the current manual.

*Note:* A Node is essentially a specific section or topic, much like a chapter or subsection in a book.

When you are browsing through the Emacs manual you can easily search with:
- i key: for specific subjects in the current manual.
- g key: for nodes (sections).
- m key: for menu items within the current Info buffer.
- s key: for regular expression patterns (like words) within the current Info buffer.

For evil users after setting up evil collection for info mode:
- g-j: for next node in the current manual.
- g-k: for previous node in the current manual.
- g-G: for nodes (sections).
- g-m: for menu items within the current Info buffer.
- The other keybinds are the same
To see all the evil [[https://github.com/emacs-evil/evil-collection/blob/master/modes/info/evil-collection-info.el][keybindings]] for info mode.

Using goto-node:
- Specify a Manual: If you want to search within a particular manual, place its name in parentheses like (emacs).
- After that tell where you want to go in that manual. For example (emacs)Top, (emacs)specific section.
- If you don't type a manual name, goto-node will search the currently opened manual.

* Core Setup & Performance
These are essential settings and small tweaks that must load before any packages.
They impact the entire configuration, skipping these could result in significantly slower configuration and potential breakage of your setup.

** Startup Performance
Core performance tweaks moved to early-init.el
See: [[https://github.com/doomemacs/doomemacs/issues/310][Why is doom emacs so fast?]]

*** Lexical-bindings
Gives better performance, lexical closures, and code safety, allowing local variables to remain truly local.
#+begin_src emacs-lisp
    ;; -*- lexical-binding: t; -*-
#+end_src

*** Early-Init.el
This file is loaded before anything else.
Most of the performance tweaks are there.
We can configure things before the GUI or other packages are loaded.

** Auto-tangle Configuration file
Auto-Tangle Org configuration file for better startup times, it refreshes the package-quickstart file.
We'll cover package quickstart in the package manager section later.

If you like to auto tangle an Org file, don't forget to add the following line to the top of your Org document:
(#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the init.el file won't update on change!
To fix this, you need to find this file (C-x C-f), fix the error and press C-c C-v t to tangle it manually.

This snippet adds a hook to org-mode buffers so that start/org-babel-tangle-config gets executed each time such a buffer gets saved.
This function checks to see if the file being saved is the init.org file you’re looking at right now, and if so,
automatically exports the configuration here to the associated output files.
#+begin_src emacs-lisp
    (defun start/org-babel-tangle-config ()
      "Automatically tangle our init.org config file and refresh package-quickstart when we save it. Credit to Emacs From Scratch for this one!"
      (interactive)
      (when (string-equal (file-name-directory (buffer-file-name))
                          (expand-file-name user-emacs-directory))
        ;; Dynamic scoping to the rescue
        (let ((org-confirm-babel-evaluate nil))
          (org-babel-tangle)
          (package-quickstart-refresh)
          )))

    (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-config)))
#+end_src

** Show startup time
#+begin_src emacs-lisp
  (defun start/display-startup-time ()
    (interactive)
    (message "Emacs loaded %d packages in %s with %d garbage collections."
  		   (length package-activated-list)
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

** Package manager
Emacs comes witha builtin package manager, called package.el and we will use it.

Alternative package managers (straight.el, elpaca, etc.) are useful if you want:
- Faster package installation.
- Lock file support for recovery if something goes wrong.
- Packages that are cloned as Git (or other) repositories, not as opaque tarballs.
- Better UI
- Async support

If you are interested in using other package managers, check out their git repositories.
To learn more about why something like [[https://github.com/doomemacs/doomemacs/blob/master/docs/faq.org#why-does-doom-use-straightel-and-not-packageel][doomemacs uses]] straight.el not package.el.

In my experience Package.el is not slow and gets the job done.

To update/upgrade packages, use the package-upgrade-all command.
Package.el has a UI. Check it out with M-x list-packages.

*** Use-package
A macro that allows you to isolate package configuration in your .emacs file in a way that is both performance-oriented and, well, tidy.
We use it because it makes package configuration really easy.

With Emacs 29 use-package is now built-in.

This code eliminates the need to type :ensure t for each package download.
Instead, you'll only need to use :ensure nil when you want to explicitly prevent a package from being downloaded.
#+begin_src emacs-lisp
    (require 'use-package-ensure) ;; Load use-package-always-ensure
    (setq use-package-always-ensure t) ;; Always ensures that a package is installed
#+end_src

**** Most used parts of use-package
Here is some notes on what each use-package keyword does.
For more check out the use-package documentation to see how powerful it is:
C-h i: g for goto-node: Type (use-package)Top

This code block is not tangled, it is just an example.
#+begin_src emacs-lisp :tangle no
    ;; Configure the 'foo' package
    ;; You can also use (use-package emacs) to customize Emacs with use-package.
    (use-package foo
      :init (message "Before")    ;; execute code Before a package is loaded.
      :config (message "After")   ;; execute code After a package is loaded.
      :custom (foovar t)          ;; Customization of package custom variables same as setq.
      :ensure t                   ;; Ensure the package is installed if it's not already.

      ;; These are also used for lazy loading.
      ;; Don't load the package until these are not true.
      :bind ("C-." . myfunc)      ;; Defer package loading until keybindings are invoked.
      :after (mypackage)          ;; Load package after specified packages have been loaded.
      ;; If you don't know what a hook is:
      ;; C-h i: g for goto-node: Type (emacs)Hooks
      :hook (myhook . myfunc)     ;; Add functions to specified hooks when the package is loaded.

      :command (bar)              ;; Define commands provided by the package to be lazy-loaded.
      :defer t                    ;; Only load this package if it's explicitly needed or a command/hook associated with it is called.
      ;; Install package with package.el from source.
      :vc (:url "<You git repo url>"
                :branch "main"
                :rev :newest) ;; Use latest commit
      )
#+end_src

*** Setting package repositories
Like Linux distributions, Emacs uses repositories to manage its packages. We add
MELPA (Milkypostman's Emacs Lisp Package Archive) to the list of package archives.
This allows you to install packages from this widely-used repository, similar to how
pip works for Python or npm for Node.js.

While Emacs comes with ELPA (Emacs Lisp Package Archive) configured by default, which
contains packages that meet specific licensing criteria, MELPA offers a broader range
of packages and is considered the standard for Emacs users.

You can also add more package archives later as needed.
#+begin_src emacs-lisp
    (setq package-archives '(("melpa" . "https://melpa.org/packages/") ;; Sets default package repositories
                             ("elpa" . "https://elpa.gnu.org/packages/")))
#+end_src

*** Package quickstart
Improves startup times by allowing Emacs to precompute and generate a single, large autoload file.
Instead of re-computing them on every startup.

The larger your configuration, the more it will be felt at startup.

However, if you enable this, you'll need to manually run the package-quickstart-refresh
command whenever your package activations change, such as when you modify the package-load-list value.
We put it inside Auto-tangle hook so when we save this file it runs it automatically.

As I tested, it makes startup about 0.1 seconds faster.
Avg:
- Off: 0.66 sec
- On:  0.59 sec

Package quickstart only works with package.el.
If you plan to use a different package manager, remember to remove this section and the package-quickstart-refresh line in the Auto-tangle hook.
#+begin_src emacs-lisp
    (setq package-quickstart t) ;; For blazingly fast startup times, this line makes startup miles faster
#+end_src

*** Package Async
Simple library for asynchronous processing in Emacs.
Makes package installation about 30 sec faster.
Only works with package.el.
#+begin_src emacs-lisp
    (use-package async
      :defer
      :custom
      (dired-async-mode t)
      (async-bytecomp-package-mode t)
      (async-bytecomp-allowed-packages '(all))
      (async-package-do-action t))
#+end_src

** Good Defaults
#+begin_src emacs-lisp
  (use-package emacs
    :custom
    ;; Still needed for terminals
    (menu-bar-mode nil)         ;; Disable the menu bar
    (scroll-bar-mode nil)       ;; Disable the scroll bar
    (tool-bar-mode nil)         ;; Disable the tool bar
    (fringe-mode nil)            ;; add space on left edge, prevent mvmt by relative numbers

    (delete-selection-mode t)   ;; Enable replacing selected text with typed text
    (electric-indent-mode nil)  ;; Turn off the weird indenting that Emacs does by default.
    (electric-pair-mode t)      ;; Turns on automatic parens pairing

    (blink-cursor-mode nil)     ;; Don't blink cursor
    (global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed
    (use-short-answers t)   ;; Since Emacs 29, `yes-or-no-p' will use `y-or-n-p'

    (recentf-mode t) ;; Enable recent file mode
    ;;(context-menu-mode t) ;; Right-click menu

    (global-visual-line-mode t)           ;; Enable line wrapping
    (global-display-line-numbers-mode t)  ;; Display line numbers
    (display-line-numbers-type 'relative) ;; Relative line numbers
    (global-hl-line-mode t)               ;; Highlight current line
    (save-place-mode 1)          ;; Enable saving the place in files for easier return.

    (native-comp-async-report-warnings-errors 'silent) ;; Don't show native comp errors
    (warning-minimum-level :error) ;; Only show errors in warnings buffer

    (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling
    (scroll-conservatively 10) ;; Smooth scrolling
    (scroll-margin 8)    ;; how many rows to retain at top and bottom of screen always

    (pixel-scroll-precision-mode t) ;; Precise pixel scrolling. i.e. smooth scrolling (GUI only)
    (pixel-scroll-precision-use-momentum nil)

    (indent-tabs-mode 1) ;;Use spaces & tabs for indentation
    (tab-width 4)
    (sgml-basic-offset 4) ;; Set Html mode indentation to 4
    (c-ts-mode-indent-offset 4) ;; Fix weird indentation in c-ts (C, C++)
    (go-ts-mode-indent-offset 4) ;; Fix weird indentation in go-ts
    (modify-coding-system-alist 'file "" 'utf-8)    ;; Set the default coding system for files to UTF-8.

    (display-fill-column-indicator-column 80) ;; Set line length indicator to 80 characters
    (whitespace-style '(face tabs tab-mark trailing))

    (make-backup-files nil) ;; Stop creating ~ backup files
    (auto-save-default nil)  ;; Stop creating # auto save files
    (create-lockfiles nil)   ;; stop creating lock files
    (delete-by-moving-to-trash t)  ;; move to Trash folder instead of permanently deleting them

    (inhibit-startup-screen t)   ;; Disable welcome screen
    (inhibit-startup-message t)                     ;; Disable the startup message when Emacs launches.
    (initial-scratch-message "")                    ;; Clear the initial message in the *scratch* buffer.

    (treesit-font-lock-level 4)                     ;; Use advanced font locking for Treesit mode.
    (truncate-lines t)                              ;; Enable line truncation to avoid wrapping long lines.
    (use-dialog-box nil)                            ;; Disable dialog boxes in favor of minibuffer prompts.
    (use-short-answers t)                           ;; Use short answers in prompts for quicker responses (y instead of yes)
    :hook
    (prog-mode . hs-minor-mode) ;; Enable folding hide/show globally
    ;; (prog-mode . display-fill-column-indicator-mode) ;; Display line length indicator on line 100
    (prog-mode . whitespace-mode)
    (prog-mode . display-line-numbers-mode)  ;; display line numbers in most progrmming modes
    ((term-mode shell-mode eshell-mode org-mode) . (lambda () (display-line-numbers-mode 0))) ;; Disable line numbers in terminal modes & org-mode

    ;; Add a hook to run code after Emacs has fully initialized.
    ;; TODO: make a list of cool quotes id like to see on startup, and place them here
    ;; to be displayed randomly
    (after-init . (lambda ()
                    (message "Emacs has fully loaded. This code runs after startup.")
                    (with-current-buffer (get-buffer-create "*scratch*")
                        (insert (format
                                ";;    Welcome to Emacs!\n;;    Don't let this darkness fool you...\n;;\n\n"
  				    (emacs-init-time)
                                (length package-activated-list))))))
    :config
    ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
    (setq custom-file (locate-user-emacs-file "custom-vars.el"))
    (load custom-file 'noerror 'nomessage)   ;; Load the custom file quietly, ignoring errors.

    ;; By default emacs gives you access to a lot of *special* buffers, while navigating with [b and ]b,
    ;; this might be confusing for newcomers. This settings make sure ]b and [b will always load a
    ;; file buffer. To see all buffers use M-x ibuffer, or <leader> b s
    (defun skip-these-buffers (_window buffer _bury-or-kill)
        "Function for `switch-to-prev-buffer-skip'."
        (string-match "\\*[^*]+\\*" (buffer-name buffer)))
    (setq switch-to-prev-buffer-skip 'skip-these-buffers)

    :bind (
           ([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
           ;; Zooming In/Out
           ("C-+" . text-scale-increase)
           ("C-=" . text-scale-increase)
           ("C--" . text-scale-decrease)
           ("<C-wheel-up>" . text-scale-increase)
           ("<C-wheel-down>" . text-scale-decrease)
           ))
#+end_src

** Dired
In Emacs, the `dired' package provides a powerful and built-in file manager
that allows you to navigate and manipulate files and directories directly
within the editor. If you're familiar with `oil.nvim', you'll find that
`dired' offers similar functionality natively in Emacs, making file
management seamless without needing external plugins.

This configuration customizes `dired' to enhance its usability. The settings
below specify how file listings are displayed, the target for file operations,
and associations for opening various file types with their respective applications.
For example, image files will open with `feh', while audio and video files
 will utilize `mpv'.

The 'dired-open' package allowsopening files using external programs easily, by using the
RETURN key, normally, the command i'd have to use in dired is 'dired-guess-shell-alist-user'
thats isnt very accurate, and alsoactivated by pressing the '&' key.

 #+begin_src emacs-lisp
    ;; NOTE: some nice defaults
    ;; C - copy files
    ;; D - delete file
    ;; R - rename file
    ;; Z- compress/uncompress directory
    ;; %l - lowercase name
    ;; %u - uppercase name
    ;; M - chmod
    ;; O - chown
    ;; m - mark individual files/directories for operation
    ;; u - undo mark for single dir/file
    ;; U - unmark everything
    ;; tm - toggle inverse mark selection
    ;; */ - mark all directories for mass operation, copy, rename, delete
    ;; M-Return - previes files contents
   (use-package dired
     :ensure nil                                                ;; This is built-in, no need to fetch it.
     :hook
     (rfn-eshadow-update-overlay . vertico-directory-tidy) ;; clear old path and keep only the current one
     :custom
     (dired-listing-switches "-lah --group-directories-first")  ;; Display files in a human-readable format and group directories first.
    (dired-kill-when-opening-new-dired-buffer t)) ;; Dired don't create new buffer when opeing new dires instance


   ;;source: https://github.com/Fuco1/dired-hacks#dired-open
    (use-package dired-open
    :after dired
    :custom
    (dired-open-extensions '(("png"  . "feh")
                            ("jpeg" . "feh")
                            ("jpg"  . "feh")
                            ("gif"  . "feh")
                            ("tiff" . "feh")
                            ("mkv"  . "mpv")
                            ("mp[34]" . "mpv")
                            ("webm" . "mpv")
                            ("pdf"  . "zathura")
                            ("epub" . "zathura")
                            (""     . "xdg-open")))) ;; for all others, ask user what to open with
 #+end_src

* Important to load first
Packages that we want to load first so we have them as soon as possible if something breaks.
** Evil Mode
An extensible vi/vim layer for Emacs.
For users who find Emacs's native keybindings less intuitive.
It integrates Vim's editing style into Emacs, giving you the best of both worlds.

If you want to use vim keybindings I left the following comments in the General Keybindings section to which lines to uncomment ;; <- evil

If you don't want to interfere with the original keybindings.
You can also try out [[https://github.com/meow-edit/meow][meow]] which is Yet another modal editing on Emacs.

Notes:
- You can toggle evil mode with C-z.
- To paste without yank select the text and use P. This line is especially for ThePrimeagen :)

#+begin_src emacs-lisp
  (use-package evil
    :hook (after-init . evil-mode)
    :init
    (evil-mode)
    :custom
    (evil-want-keybinding nil)    ;; Disable evil bindings in other modes (It's not consistent and not good)
    (evil-want-C-u-scroll t)      ;; Set C-u to scroll up
    (evil-want-C-i-jump nil)      ;; Disables C-i jump
    (evil-undo-system 'undo-fu)   ;; C-r to redo, using 'undo-fu'
    (evil-want-fine-undo t)
    ;; (evil-respect-visual-line-mode t) ;; Move in wrap lines
    ;; Unmap keys in 'evil-maps. If not done, org-return-follows-link will not work
    :bind (:map evil-motion-state-map
                ("SPC" . nil)
                ("RET" . nil)
                ("TAB" . nil)))
  #+end_src


*** Evil Collection
The `evil-collection' package enhances the integration of `evil-mode' with various
built-in and third-party packages. It provides a better modal experience by remapping
keybindings and commands to fit the `evil' style.

#+begin_src emacs-lisp
      (use-package evil-collection
        :after evil
        :config
        ;; Setting where to use evil-collection)
        (setq evil-collection-mode-list '(dired ibuffer magit corfu consult info (package-menu package) bookmark))
        (evil-collection-init))
#+end_src

*** Evil Surround
The `evil-surround' package provides text object surround
functionality for `evil-mode'. This allows for easily adding,
changing, or deleting surrounding characters such as parentheses,
quotes, and more.

With this you can change 'hello there' with ci'" to have
"hello there" and cs"<p> to get <p>hello there</p>.
More examples here:
- https://github.com/emacs-evil/evil-surround?tab=readme-ov-file#examples

#+begin_src emacs-lisp
      (use-package evil-surround
          :config
          (global-evil-surround-mode 1))
#+end_src

*** Evil Tutor
Getting acquainted with evil mode in emacs.

#+begin_src emacs-lisp
  (use-package evil-tutor)
#+end_src

** General Keybindings
A keybinding framework to set keybindings easily.

We use general because it gives:
- a convenient method for binding keys.
- easy leader key integration.
- good evil-mode and which-key support.
- a consistent and unified interface for managing keybinds.
And it is also really customizable.

Note: The Leader key is what you will press when you want to access your keybindings: C-SPC + .  Find file
#+begin_src emacs-lisp
              (defun start/open-init-file ()
                "Open init.org configuration file"
                (interactive)
                (find-file "~/.config/emacs/init.org"))

              (defun start/reload-config()
                "Reload Emacs config"
                (interactive)
                (load-file "~/.config/emacs/init.el"))

              (use-package general
                :after (evil) ;; <- evil
                :config
                (general-evil-setup) ;; <- evil

                ;; Set up 'SPC' as the leader key
                (general-create-definer start/leader-keys
                  :states '(normal insert visual motion emacs) ;; <- evil
                  :keymaps 'override
                  :prefix "SPC"
                  :global-prefix "M-SPC") ;; Set global leader key so we can access our keybindings from any state

                (start/leader-keys
                 ;; buffers
                  "b" '(:ignore t :wk "buffers")
                  "n" '(next-buffer :wk "buffer [n]ext")
                  "p" '(previous-buffer :wk "buffer [p]revious")
                  "w" '(save-buffer :wk "buffer [w]rite")
                  "b s" '(consult-buffer :wk "[b]uffer [s]witch")
                  "b k" '(kill-current-buffer :wk "[b]uffer [k]ill")
                  "b x" '(kill-current-buffer :wk "[b]uffer [k]ill")
                  "b r" '(revert-buffer :wk "[b]uffer [r]eload")

                  ;; files
                  "f" '(:ignore t :wk "files")
                  "f c" '((lambda () (interactive) (find-file "~/.dotfiles/.config/emacs/init.org")) :wk "[f]ind emacs [c]onfig")
                  "f f" '(find-file :wk "[f]ind [f]ile")    ;; telescope PTSD
                  "f r" '(consult-recent-file :wk "[f]ind [r]ecent file")
                  "f h" '(consult-imenu :wk "[f]ind by [h]eadings in buffer")
                  "f p" '(project-find-file :wk "find [f]ile in [p]roject")
                  "f w" '(consult-line :wk "[f]ind [w]ord by grep in file")  ;; equal to '/' using evil
                  "f g" '(consult-grep :wk "[f]ind file by [g]rep in directory")
                  "f s" '(sudo-edit :wk "edit current [f]ile with [s]udo priviledges")
                  "f S" '(sudo-edit-find-file :wk "[f]ind file to edit with [s]udo priviledges")

                  ;; windows
                  ;; navigate windows with basic C-w w/h/j/k/l keys
                  "-" '(evil-window-split :wk "[-] split window horizontally")
                  "\\" '(evil-window-vsplit :wk "[|] split window vertically")
                  "x" '(evil-window-delete :wk "close window")

                  ;; magit
                  "g" '(:ignore t :wk "git")
                  "g g" '(magit-status :wk "ma[g]it [g]it status")
                  "g s" '(magit-diff-buffer-file :wk "current file [g]it [s]tatus")

                  ;; dired
                  "d" '(:ignore t :wk "dired")
                  "d d" '(dired :wk "[d]ire[d] open")
                  "d j" '(dired-jump :wk "[d]ired [j]ump to current") ;; open current file in dired

                  ;; Evaluate
                  "e" '(:ignore t :wk "Evaluate")
                  "e b" '(eval-buffer :wk "[e]valuate elisp in [b]uffer")
                  "e e" '(eval-expression :wk "[e]valuate elisp [e]xpression")
                  "e r" '(eval-region :wk "[e]valuate elisp [r]egion")
                  "e d" '(eval-defun :wk "[e]valuate [d]efun containing/after point")
                  "e l" '(eval-last-sexp :wk "[e]valuate elisp expression before point")

                  ;; better help with helpful
                  "h" '(:ignore t :wk "help")
                  "h f" '(helpful-callable :wk "[h]elp [f]unction")
                  "h v" '(helpful-variable :wk "[h]elp [v]ariable")
                  "h k" '(helpful-key :wk "[h]elp [k]eymap")
                  "h c" '(helpful-command :wk "[h]elp [c]ommand")
                  "h m" '(describe-mode :wk "[h]elp current [m]ode")

                  ;; misc
                  "." '(ansi-term :wk "open terminal[.]")
                  "/" '(display-line-numbers-mode :wk "toggle line numbers")

                  ;; ;; Org mode
                  ;; "m" '(:ignore t :wk "Org")
                  ;; "m a" '(org-agenda :wk "Org agenda")
                  ;; "m e" '(org-export-dispatch :wk "Org export dispatch")
                  ;; "m i" '(org-toggle-item :wk "Org toggle item")
                  ;; "m t" '(org-todo :wk "Org todo")
                  ;; "m B" '(org-babel-tangle :wk "Org babel tangle")
                  ;; "m T" '(org-todo-list :wk "Org todo list")
                  ;; "m b" '(:ignore t :wk "Tables")
                  ;; "m b -" '(org-table-insert-hline :wk "Insert hline in table")
                  ;; "m d" '(:ignore t :wk "Date/deadline")
                  ;; "m d t" '(org-time-stamp :wk "Org time stamp")


                  ;; ;; Projectile
                  ;; "p" '(projectile-command-map :wk "Projectile")
                  ;; "s p" '(projectile-discover-projects-in-search-path :wk "Search for projects")

                  ;; "q" '(flymake-show-buffer-diagnostics :wk "Flymake buffer diagnostic")

                  ;; ;; Registers
                  ;; "m" '(:ignore t :wk "Bookmarks & Registers")
                  ;; "m s" '(consult-register :wk "Consult register")
                  ;; "m k" '(jump-to-register :wk "Jump to register")
                  ;; "m e" '(point-to-register :wk "Point to register")
                  ;; ;; Bookmarks
                  ;; "m a" '(bookmark-set :wk "Bookmark Set")
                  ;; "m d" '(bookmark-jump :wk "Bookmark Jump")
                  ;; "m r" '(bookmark-delete :wk "Bookmark Delete")
                  ;; "m R" '(bookmark-delete-all :wk "Bookmark Delete All")
                  ;; "m l" '(bookmark-bmenu-list :wk "Bookmark bmenu list")
                  ;; "m c" '(consult-bookmark :wk "Consult Bookmark")


                  ;; ;; eglot
                  ;; "e" '(:ignore t :wk "Languages")
                  ;; "e e" '(eglot-reconnect :wk "Eglot Reconnect")
                  ;; "e d" '(eldoc-doc-buffer :wk "Eldoc Buffer")
                  ;; "e f" '(eglot-format :wk "Eglot Format")

                  ;; "e l" '(consult-flymake :wk "Consult Flymake")
                  ;; "e n" '(flymake-goto-next-error :wk "Flymake next error")
                  ;; "e p" '(flymake-goto-prev-error :wk "Flymake previous error")

                  ;; "e a" '(eglot-code-actions :wk "Eglot code actions")
                  ;; "e r" '(eglot-rename :wk "Eglot Rename")
                  ;; "e i" '(xref-find-definitions :wk "Find definition")
                  ;; "e s" '(xref-find-references :wk "Find references")

                  ;; "e v" '(:ignore t :wk "Elisp")
                  ;; "e v b" '(eval-buffer :wk "Evaluate elisp in buffer")
                  ;; "e v r" '(eval-region :wk "Evaluate elisp in region")


                  ;; ;; mason
                  ;; "r" '(:ignore t :wk "Reload & Packages") ;; To get more help use C-h commands (describe variable, function, etc.)
                  ;; ;; Mason.el
                  ;; "r m" '(mason-manager :wk "Mason manager")
                  ;; "r i" '(mason-install :wk "Mason install")
                  ;; ;; Package-menu-mode
                  ;; "r p" '(list-packages :wk "List packages")
                  ;; "r c" '(package-menu-clear-filter :wk "Package clear filters")
                  ;; "r n" '(package-menu-filter-by-name :wk "Package filter by name")
                  ;; "r N" '(package-menu-filter-by-name-or-description :wk "Package filter by name or descriptions")
                  ;; "r s" '(package-menu-filter-by-status :wk "Package filter by status")
                  ;; "r u" '(package-menu-filter-upgradable :wk "Package filter by upgradable")
  ))

        ;; Fix general.el leader key not working instantly in messages buffer with evil mode
        ;; (use-package emacs
        ;;  :after (evil general)
        ;;  :ghook ('after-init-hook
        ;;          (lambda (&rest _)
        ;;            (when-let ((messages-buffer (get-buffer "*Messages*")))
        ;;              (with-current-buffer messages-buffer
        ;;                (evil-normalize-keymaps))))
        ;;          nil nil t))
#+end_src

*** Creating keybindings the built in way
If you want to use the built in methods I recommend using these ones:

#+begin_src emacs-lisp
  ;; (define-key KEYMAP KEY DEF)
  ;; (global-set-key KEY COMMAND)
  ;; (use-package :bind (  ))

  (evil-define-key 'normal 'global (kbd "] d") 'flymake-goto-next-error) ;; Go to next Flymake error
  (evil-define-key 'normal 'global (kbd "[ d") 'flymake-goto-prev-error) ;; Go to previous Flymake error

  ;; Diff-HL navigation for version control
  (evil-define-key 'normal 'global (kbd "] g") 'diff-hl-next-hunk) ;; Next diff hunk
  (evil-define-key 'normal 'global (kbd "[ g") 'diff-hl-previous-hunk) ;; Previous diff hunk

  ;; Buffer management keybindings
  (evil-define-key 'normal 'global (kbd "] b") 'next-buffer) ;; Switch to next buffer
  (evil-define-key 'normal 'global (kbd "[ b") 'previous-buffer) ;; Switch to previous buffer

  ;; Tab navigation
  (evil-define-key 'normal 'global (kbd "] t") 'tab-next) ;; Go to next tab
  (evil-define-key 'normal 'global (kbd "[ t") 'tab-previous) ;; Go to previous tab

  ;; todo navigation
  (evil-define-key 'normal 'global (kbd "] T") 'hl-todo-next) ;; Go to next todo
  (evil-define-key 'normal 'global (kbd "[ T") 'hl-todo-previous) ;; Go to previous todo

  ;; ;; LSP commands keybindings
  ;; TODO: make this work? moreso the 'K' and 'gd'
  ;; (evil-define-key 'normal lsp-mode-map
  ;;                  ;; (kbd "gd") 'lsp-find-definition                ;; evil-collection already provides gd
  ;;                  (kbd "gr") 'lsp-find-references                   ;; Finds LSP references
  ;;                  (kbd "<leader> c a") 'lsp-execute-code-action     ;; Execute code actions
  ;;                  (kbd "<leader> r n") 'lsp-rename                  ;; Rename symbol
  ;;                  (kbd "gI") 'lsp-find-implementation               ;; Find implementation
  ;;                  (kbd "<leader> l f") 'lsp-format-buffer)          ;; Format buffer via lsp


  ;; (defun ek/lsp-describe-and-jump ()
  ;;   "Show hover documentation and jump to *lsp-help* buffer."
  ;;   (interactive)
  ;;   (lsp-describe-thing-at-point)
  ;;   (let ((help-buffer "*lsp-help*"))
  ;;     (when (get-buffer help-buffer)
  ;;       (switch-to-buffer-other-window help-buffer))))

  ;; FIXME: terrible UB at times, figure out why
   ;; Commenting functionality for single and multiple lines
(evil-define-key 'normal 'global (kbd "gc")
                (lambda ()
                    (interactive)
                    (if (not (use-region-p))
                        (comment-or-uncomment-region (line-beginning-position) (line-end-position)))))

   (evil-define-key 'visual 'global (kbd "gc")
                    (lambda ()
                      (interactive)
                      (if (use-region-p)
                          (comment-or-uncomment-region (region-beginning) (region-end)))))
#+end_src
To read more about using the built in methods, check out this awesome article from [[https://www.masteringemacs.org/article/mastering-key-bindings-emacs][masteringemacs]].

** Undo
Undotree like setup.

Undo Fu: Simple, stable linear undo with redo for Emacs.
Undo-fu-session: Persistent undo history

If you want to use this. Don't forget to add keybindings for undu-fu.
Evil users don't need to add keybindings for undo-fu just change evil-undo-system to undo-fu.

#+begin_src emacs-lisp
  (use-package undo-fu
  :defer
  :config
  ;; Increase undo history limits to reduce likelihood of data loss
  (setq undo-limit (* 1024 1024 64)          ;; 64mb  (default is 160kb)
      undo-strong-limit (* 1024 1024 96)   ;; 96mb  (default is 240kb)
      undo-outer-limit (* 1024 1024 960))) ;; 960mb (default is 24mb)

  (use-package undo-fu-session
      :hook (after-init . undo-fu-session-global-mode)
      :custom (undo-fu-session-incompatible-files '("\\.gpg$" "/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
      :config
      (when (executable-find "zstd")
      ;; There are other algorithms available, but zstd is the fastest, and speed
      ;; is our priority within Emacs
      (setq undo-fu-session-compression 'zst)))

#+end_src

* Appearance
Set fonts in the early-init.el file
** Set Theme
Set monokai theme, if you want some themes try out doom-themes.
Use consult-theme to easily try out themes (*Epilepsy* Warning).
#+begin_src emacs-lisp
    ;; NOTE: best monokai look-alike imo. look into the modus-* and make mods
    ;; (use-package monokai-pro-theme
    ;;     :config
    ;;     (load-theme 'monokai-pro-classic t))

  (use-package monokai-theme
    :config
    (load-theme 'monokai t))

    ;; use this when building your own theme
    ;; (add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
    ;; (load-theme 'monokai t)

#+end_src

** Doom Modeline
A fancy, fast and customizable mode-line.

#+begin_src emacs-lisp
    (use-package doom-modeline
      :custom
      (doom-modeline-height 30)
      (doom-modeline-buffer-file-name-style 'auto)  ;; Set the buffer file name style to just the buffer name (without path).
      (doom-modeline-project-detection 'project)           ;; Enable project detection for displaying the project name.
      (doom-modeline-buffer-name t)                        ;; Show the buffer name in the mode line.
      (doom-modeline-vcs-max-length 25)                    ;; Limit the version control system (VCS) branch name length to 25 characters.
      (doom-modeline-position-line-format '("LOC: %l"))
      (doom-modeline-percent-position nil)
      (doom-modeline-buffer-encoding nil)
      (doom-modeline-total-line-number t)
      :hook
      (after-init . doom-modeline-mode)
      ;; :config
      ;; ;; Redefine the default 'main' modeline layout to your exact specifications
      ;; (doom-modeline-def-modeline 'main
      ;;     ;; LEFT SIDE
      ;;     ;; 1. Evil mode (modals)
      ;;     ;; 2. Buffer name (buffer-info)
      ;;     ;; 3. Diagnostics (checker)
      ;;     ;; 4. Space / The rest (vcs for git branch, etc.)
      ;;     '(modals vcs buffer-info)

      ;;     ;; RIGHT SIDE
      ;;     ;; Miscellaneous info, major mode, and LOC (buffer-position) at the absolute far right
      ;;     '(misc-info minor-modes major-mode process buffer-position))
  	)

#+end_src

** Nerd Icons
This is an icon set that can be used with dired, ibuffer and other Emacs packages.
Don't forget to M-x install 'nerd-icons-install-fonts' to install the resource fonts, if they are not already
on your system.

We use nerd-icons because it supports both GUI and TUI unlike all-the-icons.
Also Doom modeline requires nerd icons.
#+begin_src emacs-lisp
    (use-package nerd-icons :defer)

    (use-package nerd-icons-dired
      :hook (dired-mode . nerd-icons-dired-mode))

    (use-package nerd-icons-ibuffer
      :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

* Development
** Eglot
Built in Emacs client for the Language Server Protocol.
We use Eglot because it is fast and minimal.
For more: C-h i: g: (eglot)Top

Eglot does not automatically download LSP servers. It requires separate download.
The easiest way to install LSP servers is with a package manager like mason.el.

If you can't use a package manager you can do the following:
- Download the server (e.g. from github)
- Add the binary/executable to your path.
- Or customize the eglot-server-programs list.
To control how a LSP server is started customize the eglot-server-programs list.

There are many alternative LSP clients, one of them is LSP-mode.
Which has more features and supports automatic language server installation.
But it's bigger, so it has more moving parts.

We don't use it because Eglot is more than enough for most people.
If you want to use LSP mode check out their [[https://emacs-lsp.github.io/lsp-mode/][documentation]] or the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] page for more information.
#+begin_src emacs-lisp
  (use-package eglot
    :ensure nil ;; Don't install eglot because it's now built-in
    :hook ((c-mode
  		 c++-mode ;; Autostart lsp servers for a given mode
           python-base-mode                             ;; Enable LSP for Python
  		 lua-mode ;; Lua-mode needs to be installed
           js-mode                                      ;; Enable LSP for JavaScript
           typescript-ts-base-mode                      ;; Enable LSP for TypeScript
           ;; css-mode                                     ;; Enable LSP for CSS
           ;; go-ts-mode                                   ;; Enable LSP for Go
           ;; js-ts-mode                                   ;; Enable LSP for JavaScript (TS mode)
           ;; prisma-mode                                  ;; Enable LSP for Prisma
           ;; tsx-ts-mode                                  ;; Enable LSP for TSX
           ;; ruby-base-mode                               ;; Enable LSP for Ruby
           ;; rust-ts-mode                                 ;; Enable LSP for Rust
           web-mode) . eglot-ensure)
    :custom
    ;; Good default
    (eglot-events-buffer-size 0) ;; No event buffers (LSP server logs)
    (eglot-autoshutdown t);; Shutdown unused servers.
    (eglot-report-progress nil) ;; Disable LSP server logs (Don't show lsp messages at the bottom, java)
    )
#+end_src

** Mason.el
Package manager for LSP, DAP, linters, and more for the Emacs Operating System.
I waited so long for a package like this.
If you plan to use something like LSP-mode don't forget to remove this.
Check out more language servers in the [[https://mason-registry.dev/registry/list][mason registry]].

#+begin_src emacs-lisp
    (use-package mason
        :hook (after-init . mason-ensure)
        :config
    (mason-setup))

    (mason-setup
      (dolist (pkg '("basedpyright"
                    "jdtls"
                    "clangd"
                    "cpptools"
                    "json-lsp"
                    "yaml-language-server"
                    "typescript-language-server"
                    "bash-language-server"
                    "docker-compose-language-service"))
        (unless (mason-installed-p pkg)
          (ignore-errors (mason-install pkg)))))
#+end_src

** Sideline-flymake
Flymake is an on-the-fly syntax checking extension that provides real-time feedback
about errors and warnings in your code as you write. This can greatly enhance your
coding experience by catching issues early.

The configuration below activates Flymake mode in programming buffers, showing errors
on the sideline.
#+begin_src emacs-lisp
      (use-package sideline-flymake
        :hook ((flymake-mode . sideline-mode)
  			 (prog-mode . flymake-mode))
        :custom
        (sideline-flymake-display-mode 'line) ;; Show errors on the current line
        (sideline-backends-right '(sideline-flymake)))
#+end_src

** Yasnippet
A template system for Emacs. And yasnippet-snippets is a snippet collection package.
To use it write out the full keyword (or use autocompletion) and press Tab.
#+begin_src emacs-lisp
    (use-package yasnippet
      :hook (prog-mode . yas-minor-mode))

    (use-package yasnippet-snippets :defer)

    (defun start/corfu-yas-tab-handler ()
      "Prioritize corfu over yasnippet when yasnippet is active"
      (interactive)
      ;; There is no direct way to get if corfu is currently displayed so we watch the completion index
      (if (> corfu--index -1)
          (corfu-complete)
        (yas-next-field-or-maybe-expand)
        ))
    (use-package emacs
      :after (yasnippet corfu)
      :bind
      (:map yas-keymap
            ("TAB" . start/corfu-yas-tab-handler)))
#+end_src

** Tree-Sitter
A parser generator tool and an incremental parsing library.
Check out TJ's [[https://www.youtube.com/watch?v=09-9LltqWLY][video]] to learn why you should use it.

With Emacs 29 Tree-Sitter is now built-in. You may need to compile Emacs from source to have it enabled.
You also need to have a compiler installed so Emacs can compile the parsers into a shared library.
For more info about how to use Tree-Sitter check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][masteringemacs]] article.

Using Tree-Sitter is somewhat hacky because it requires you to:
- manually manage a source list of the parsers you want to use.
- remap the major modes you want to use.
You can also use treesit-auto, but it is updated quite slowly so we don't use it.

To explore the current buffer's syntax tree, use the treesit-explore-mode command.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp
      (setq treesit-language-source-alist
            '((bash "https://github.com/tree-sitter/tree-sitter-bash")
              (cmake "https://github.com/uyha/tree-sitter-cmake")
              (make "https://github.com/alemuller/tree-sitter-make")
              (c "https://github.com/tree-sitter/tree-sitter-c")
              (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
              (elisp "https://github.com/Wilfred/tree-sitter-elisp")
              (python "https://github.com/tree-sitter/tree-sitter-python")
              (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
              (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
              (yaml "https://github.com/ikatyang/tree-sitter-yaml")
              ;; (json "https://github.com/tree-sitter/tree-sitter-json")
              ;; (markdown "https://github.com/ikatyang/tree-sitter-markdown")
              ;; (rust "https://github.com/tree-sitter/tree-sitter-rust")
              ;; (toml "https://github.com/tree-sitter/tree-sitter-toml")
              ;; (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
              ;; (gdscript "https://github.com/PrestonKnopp/tree-sitter-gdscript")
              ;; (go "https://github.com/tree-sitter/tree-sitter-go")
              ;; (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
              ;; (html "https://github.com/tree-sitter/tree-sitter-html")
              ;; (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
              ;; (vue "https://github.com/ikatyang/tree-sitter-vue")
              ;; (css "https://github.com/tree-sitter/tree-sitter-css")
  ))

      (defun start/install-treesit-grammars ()
        "Install missing treesitter grammars"
        (interactive)
        (dolist (grammar treesit-language-source-alist)
          (let ((lang (car grammar)))
            (unless (treesit-language-available-p lang)
              (treesit-install-language-grammar lang)))))

      ;; Call this function to install missing grammars
      (add-hook 'after-init-hook #'start/install-treesit-grammars)

      ;; Optionally, add any additional mode remappings not covered by defaults
      (setq major-mode-remap-alist
            '((yaml-mode . yaml-ts-mode)
              (sh-mode . bash-ts-mode)
              (c-mode . c-ts-mode)
              (c++-mode . c++-ts-mode)
              (css-mode . css-ts-mode)
              (python-mode . python-ts-mode)
              (mhtml-mode . html-ts-mode)
              (javascript-mode . js-ts-mode)
              (js-json-mode . json-ts-mode)
              (typescript-mode . typescript-ts-mode)
              ;; (conf-toml-mode . toml-ts-mode)
              ;; (gdscript-mode . gdscript-ts-mode)
              ))
      (setq treesit-font-lock-level 3)

#+end_src

** Language modes
Emacs contains many “editing modes” that alter its basic behavior in
useful ways. These are divided into “major modes” and “minor modes”.
For more: C-h i: g: (emacs)Modes

Some programming languages require the installation of specific modes to fully integrate and function within Emacs.
These packages are often necessary for features like syntax highlighting, code formatting, linting, and language-specific features.

*** Lua mode
Example, how to setup a language mode.
Use C-SPC tab to uncomment the lines.
#+begin_src emacs-lisp
    (use-package lua-mode
      :mode "\\.lua\\'") ;; Only start in a lua file
#+end_src

*** Python mode
#+begin_src emacs-lisp
  (use-package python-mode
    :mode "\\.py\\'")
#+end_src

*** Org Mode
One of the things that Emacs is loved for. Org-mode is a powerful system for organizing and managing
your notes, tasks, and documents in plain text. Once you've used it for a bit, you'll understand why
people love it. Even reading about it can be inspiring!

For example, this document is effectively the source code and descriptions bound into the one document,
much like the literate programming ideas that Donald Knuth made famous.

We use an Org mode document for our Emacs configuration because it provides:
- Better organization: It lets us structure with outlines, headings, and tags.
- Literate Documentation: It's a document, not just source code.
- Fast Navigation: Quickly jump to sections with something like Imenu.

If you consider using org mode even more. Check out the [[https://github.com/minad/org-modern][org-modern]] package.
It makes org mode really beautiful.
Don't forget to remove org-superstar if you want to use it.

NOTE: For templates use C-c C-, Much easier than org-tempo
#+begin_src emacs-lisp
  (use-package org
    :ensure nil
    :defer t
    :custom
    ;; (org -edit-src-content-indentation 4) ;; Set src block automatic indent to 4 instead of 2.
    (org-return-follows-link t)   ;; Sets RETURN key in org-mode to follow links
    :hook
    (org-mode . org-indent-mode) ;; Indent text
    )
#+end_src

**** Table of Contents
#+begin_src emacs-lisp
    (use-package toc-org
      :commands toc-org-enable
      :hook (org-mode . toc-org-mode))
#+end_src

**** Org Superstar
Prettify headings and plain lists in Org mode. Modern version of org-bullets.
#+begin_src emacs-lisp
    (use-package org-superstar
      :after org
      :hook (org-mode . org-superstar-mode))
#+end_src

** Shells
*** Exec-path-from-shell
Make Emacs use the $PATH set up by the user's shell
#+begin_src emacs-lisp
    (use-package exec-path-from-shell
      :hook (after-init . exec-path-from-shell-initialize))
#+end_src

** Sudo Edit
Sudo edit allows us to edit files with sudo priviledges, if we had initially opened the files without such
priviledges.

#+begin_src emacs-lisp
        (use-package sudo-edit)
#+end_src

** Dotenv
A simple major mode to provide .env files with color highlighting
#+begin_src emacs-lisp
(use-package dotenv-mode
  :defer t)
#+end_src

* Multi File Example
** Adding the lisp directory to load-path
Adds the lisp directory to Emacs's load path to search for elisp files.
This is necessary because Emacs does not search the entire user-emacs-directory.
The directory name can be anything, just add it to the load-path.
#+begin_src emacs-lisp
    ;; (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
#+end_src

** Sourcing the files
To use the elisp files we need to load it.
Notes:
- Don't forget the file and the provide name needs to be the same.
- When naming elisp files, functions, it is recommended to use a group name (e.g. init-, start- or any custom name), so it does not get mixed up with other names, functions.
#+begin_src emacs-lisp
    ;; (require 'start-multiFileExample)
#+end_src

** Using the file
And now we can use everything from that file.
#+begin_src emacs-lisp
    ;; (start/hello)
#+end_src

* Version Control
** Magit
`magit' is a powerful Git interface for Emacs that provides a complete
set of features to manage Git repositories. With its intuitive interface,
you can easily stage, commit, branch, merge, and perform other Git
operations directly from Emacs. Magit’s powerful UI allows for a seamless
workflow, enabling you to visualize your repository's history and manage
changes efficiently.

In the Neovim ecosystem, similar functionality is provided by plugins such as
`fugitive.vim', which offers a robust Git integration with commands that
allow you to perform Git operations directly within Neovim. Another popular
option is `neogit', which provides a more modern and user-friendly interface
for Git commands in Neovim, leveraging features like diff views and staging
changes in a visual format. Both of these plugins aim to replicate and
extend the powerful capabilities that Magit offers in Emacs.
#+begin_src emacs-lisp
    (use-package transient
      :defer
      :config
      (define-key transient-map (kbd "<escape>") 'transient-quit-one)) ;; Make escape quit magit prompts

    (use-package magit
      :defer
      :custom (magit-diff-refine-hunk (quote all)) ;; Shows inline diff
      :config
      (setopt magit-format-file-function #'magit-format-file-nerd-icons) ;; Magit nerd icons
      )
#+end_src

** Diff-hl
Highlights uncommitted changes on the left side of the window (area also known as the "gutter"), allows you to
jump between and revert them selectively.

The `diff-hl' package provides visual indicators for version control changes
directly in the margin of the buffer(left-side), often called the "gutter". It shows
lines added, deleted, or changed and allows you to jump between them and revert
them selectively.

This is useful for tracking modifications while you edit files. When enabled,
it automatically activates in every buffer that has a corresponding version
control backend, offering a seamless experience.

In comparison, Neovim users often rely on plugins like `gitsigns.nvim' or
`vim-signify', which provide similar functionalities by displaying Git
changes in the gutter and offer additional features like highlighting
changed lines and displaying blame information. `diff-hl' aims to provide
a comparable experience in Emacs with its own set of customizations.
#+begin_src emacs-lisp
    (use-package diff-hl
      :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
             (magit-post-refresh . diff-hl-magit-post-refresh)
             (after-init . global-diff-hl-mode)))


#+end_src

* Completion
** Corfu
Enhances in-buffer completion with a small completion popup.
Corfu is a small package, which relies on the Emacs completion facilities and concentrates on providing a polished completion.
For more configuration options check out their [[https://github.com/minad/corfu][git repository]].
Notes:
- To enter Orderless field separator, use M-SPC.
#+begin_src emacs-lisp
  (use-package corfu
    ;; Optional customizations
    :custom
    (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto t)                 ;; Enable auto completion
    (corfu-auto-prefix 2)          ;; Minimum length of prefix for auto completion.
    (corfu-quit-no-match t)        ;; Quit if there is no match
    (corfu-popupinfo-mode t)       ;; Enable popup information
    (corfu-popupinfo-delay 0.5)    ;; Lower popup info delay to 0.5 seconds from 2 seconds
    (corfu-separator ?\s)          ;; Orderless field separator, Use M-SPC to enter separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin
    (completion-ignore-case t)

    ;; Emacs 30 and newer: Disable Ispell completion function.
    ;; Try `cape-dict' as an alternative.
    (text-mode-ispell-word-completion nil)

    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (tab-always-indent 'complete)

    (corfu-preview-current nil) ;; Don't insert completion without confirmation
    ;; Recommended: Enable Corfu globally.  This is recommended since Dabbrev can
    ;; be used globally (M-/).  See also the customization variable
    ;; `global-corfu-modes' to exclude certain modes.
    :init
    (global-corfu-mode))

  (use-package nerd-icons-corfu
    :after corfu
    :init (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

** Cape
Provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI.

We merge capfs together so they appear together in the completion list.
The ones not merged will display separately (Only their list will show up in the completion list).
Order matters. Since these functions run in sequence, the first one to return a list will prevent others from running.
Due to technical details, not all Capfs can be merged successfully (e.g cape-file).

Notes:
- Be aware when adding Capfs (Completion-at-point-functions) to the list since each of the Capfs adds a small runtime cost.
Read the [[https://github.com/minad/cape#configuration][configuration section]] in Cape's readme for more information.
#+begin_src emacs-lisp
  (use-package yasnippet-capf :defer)

  (defun start/setup-capfs ()
    "Configure completion backends"
    ;; Take care when adding Capfs to the list since each of the Capfs adds a small runtime cost.
    (let ((merge-backends (list
                           #'cape-keyword      ;; Keyword completion
                           ;; #'cape-abbrev       ;; Complete abbreviation
                           #'cape-dabbrev      ;; Complete word from current buffers
                           ;; #'cape-line         ;; Complete entire line from current buffer
                           ;; #'cape-history      ;; Complete from Eshell, Comint or minibuffer history
                           ;; #'cape-dict         ;; Dictionary completion (Needs Dictionary file installed)
                           ;; #'cape-tex          ;; Complete Unicode char from TeX command, e.g. \hbar
                           ;; #'cape-sgml         ;; Complete Unicode char from SGML entity, e.g., &alpha
                           ;; #'cape-rfc1345      ;; Complete Unicode char using RFC 1345 mnemonics
                           ;; #'snippy-capf       ;; Vscode Snippets (Snippy needs to be installed)
                           #'yasnippet-capf    ;; Yasnippet snippets
                           ))
          (seperate-backends (list
                              #'cape-file ;; Path completion
                              #'cape-elisp-block ;; Complete elisp in Org or Markdown mode
                              )))
      ;; Remove keyword completion in git commits
      (when (derived-mode-p 'git-commit-mode)
        (setq merge-backends (remq #'cape-keyword merge-backends)))

      ;; Add Elisp symbols only in Elisp modes
      (when (derived-mode-p 'emacs-lisp-mode 'ielm-mode)
        (setq merge-backends (cons #'cape-elisp-symbol merge-backends))) ;; Emacs Lisp code (functions, variables)

      ;; Add Eglot to the front of the list if it's active
      (when (bound-and-true-p eglot--managed-mode)
        (setq merge-backends (cons #'eglot-completion-at-point merge-backends)))

      ;; Create the super-capf and set it buffer-locally
      (setq-local completion-at-point-functions
                  (append
                   seperate-backends
                   (list (apply #'cape-capf-super merge-backends)))
                  )))

  (use-package cape
    :after (corfu)
    :init
    ;; Add to the global default value of `completion-at-point-functions' which is
    ;; used by `completion-at-point'.  The order of the functions matters, the
    ;; first function returning a result wins.  Note that the list of buffer-local
    ;; completion functions takes precedence over the global list.

    ;; Seperate function needed, because we use setq-local (everything is replaced)
    (add-hook 'eglot-managed-mode-hook #'start/setup-capfs)
    (add-hook 'prog-mode-hook #'start/setup-capfs)
    (add-hook 'text-mode-hook #'start/setup-capfs))
#+end_src

** Orderless
Orderless enhances completion in Emacs by allowing flexible pattern matching, by
dividing the patterns into space-separated components, thus matching candidates of the
componenets in any order.

It works seamlessly with Vertico & Corfu, enabling you to use partial strings and
regular expressions to find files, buffers, and commands more efficiently.
#+begin_src emacs-lisp
  (use-package orderless
    :defer    ;; load on demand
    :after vertico    ;; load after vertico
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** Vertico and Marginalia
- Vertico: Provides a performant and minimalistic vertical completion UI based on the default completion system.
- Savehist: Saves completion history.
- Marginalia: Adds extra metadata for completions in the margins (like descriptions).
- Nerd-icons-completion: Adds icons to completion candidates using the built in completion metadata functions.

We use these packages because they use Emacs native functions. Unlike Ivy or Helm.
One alternative is ivy and counsel, check out the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] for more inforomation.
#+begin_src emacs-lisp
  (use-package vertico
    :hook (after-init . vertico-mode)
    ;; Vim keybinds. uses C-n/p by default
    :bind (:map vertico-map
               ;; ("C-j" . vertico-next)
               ;; ("C-k" . vertico-previous)
               ("C-u" . vertico-scroll-down)
               ("C-d" . vertico-scroll-up))
    :custom
    (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    ;; :config
    ;; ;; Customize the display of the current candidate in the completion list.
    ;; ;; This will prefix the current candidate with “» ” to make it stand out.
    ;; ;; Reference: https://github.com/minad/vertico/wiki#prefix-current-candidate-with-arrow
    ;; (advice-add #'vertico--format-candidate :around
    ;;             (lambda (orig cand prefix suffix index _start)
    ;;                 (setq cand (funcall orig cand prefix suffix index _start))
    ;;                 (concat
    ;;                 (if (= vertico--index index)
    ;;                     (propertize "» " 'face '(:foreground "#80adf0" :weight bold))
    ;;                 "  ")
    ;;                 cand)))
    )

  (savehist-mode) ;; Enables save history mode

  (use-package marginalia
    :after vertico
    :config
    (marginalia-mode))

  (use-package nerd-icons-completion
    :after marginalia
    :config
    (nerd-icons-completion-mode)
    :hook
    (marginalia-mode . nerd-icons-completion-marginalia-setup))
#+end_src

** Jinx
Enchanted Spell Checker.
Don't forget to add keybindings.

Jinx can cause performance problems in large markdown files.
*To use it, remove :tangle no from the beginning of the source code block.*

#+begin_src emacs-lisp :tangle no
    (use-package jinx
      :hook (after-init . global-jinx-mode))
#+end_src

* Other packages
All the package setups that don't need much tweaking.
** Consult
Provides search and navigation commands based on the Emacs completion function.
Telescope for Emacs.
Check out their [[https://github.com/minad/consult][git repository]] for more awesome functions.

#+begin_src emacs-lisp
  (use-package consult
    ;; Enable automatic preview at point in the *Completions* buffer. This is
    ;; relevant when you use the default completion UI.
    :hook (completion-list-mode . consult-preview-at-point-mode)
    :init
    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    :config
    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    (setq consult-preview-key 'any)
    (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("C-n" "C-p"))    ;; FIXME: make this work, with instant preview?
    (setq consult-preview-key '("S-<down>" "S-<up>"))

    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    ;; (consult-customize
    ;; consult-theme :preview-key '(:debounce 0.2 any)
    ;; consult-ripgrep consult-git-grep consult-grep
    ;; consult-bookmark consult-recent-file consult-xref
    ;; consult--source-bookmark consult--source-file-register
    ;; consult--source-recent-file consult--source-project-recent-file
    ;; :preview-key "M-."
    ;; :preview-key '(:debounce 0.4 any))

    ;; By default `consult-project-function' uses `project-root' from project.el.
    ;; Optionally configure a different project root function.
     ;;;; 1. project.el (the default)
    ;; (setq consult-project-function #'consult--default-project--function)
     ;; 2. vc.el (vc-root-dir)
    ;; (setq consult-project-function (lambda (_) (vc-root-dir)))
     ;;;; 3. locate-dominating-file
    ;; (setq consult-project-function (lambda (_) (locate-dominating-file "." ".git")))
     ;;;; 4. projectile.el (projectile-project-root)
    ;; (autoload 'projectile-project-root "projectile")
    ;; (setq consult-project-function (lambda (_) (projectile-project-root)))
     ;;;; 5. No project support
    ;; (setq consult-project-function nil)
    )
#+end_src

** Helpful
An alternative to the built-in Emacs help that provides much more contextual information.

#+begin_src emacs-lisp
      ;; Note that the built-in `describe-function' includes both functions
      ;; and macros. `helpful-function' is functions only, so we provide
      ;; `helpful-callable' as a drop-in replacement.
    (use-package helpful)
#+end_src

** Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.
With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.

#+begin_src emacs-lisp
    (use-package diminish :defer)
#+end_src

** Rainbow Delimiters
Adds colors to brackets.

#+begin_src emacs-lisp
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Rainbow Mode
Adds actual color as background to any hex colors. It emulates rainbow-mode in all programming modes(prog-mode) and
org-mode.

#+begin_src emacs-lisp
    (use-package rainbow-mode
      :hook (prog-mode org-mode))
#+end_src

** Hl-todo
Highlight TODO keywords.
#+begin_src emacs-lisp
    (use-package hl-todo
      :hook
      ((prog-mode yaml-ts-mode) . hl-todo-mode)
      :config
      ;; From doom emacs
      (setq hl-todo-highlight-punctuation ":"
            hl-todo-keyword-faces
            '(;; For reminders to change or add something at a later date.
              ("TODO" warning bold)
              ;; For code (or code paths) that are broken, unimplemented, or slow,
              ;; and may become bigger problems later.
              ("FIXME" error bold)
              ;; For code that needs to be revisited later, either to upstream it,
              ;; improve it, or address non-critical issues.
              ("REVIEW" font-lock-keyword-face bold)
              ;; For code smells where questionable practices are used
              ;; intentionally, and/or is likely to break in a future update.
              ("HACK" font-lock-constant-face bold)
              ;; For sections of code that just gotta go, and will be gone soon.
              ;; Specifically, this means the code is deprecated, not necessarily
              ;; the feature it enables.
              ("DEPRECATED" font-lock-doc-face bold)
              ;; Extra keywords commonly found in the wild, whose meaning may vary
              ;; from project to project.
              ("NOTE" success bold)
              ("BUG" error bold)))
      )
#+end_src

** Indent-guide
The `indent-guide' package provides visual indicators for indentation levels
in programming modes, making it easier to see code structure at a glance.
It draws vertical lines (by default, a character of your choice) at each
level of indentation, helping to improve readability and navigation within
the code.
#+begin_src emacs-lisp
    (use-package indent-guide
      :hook
      (prog-mode . indent-guide-mode)
      :config
      (setq indent-guide-char "│")) ;; Set the character used for the indent guide.
#+end_src

** Which-Key
Which-key is a helper utility for keychords (which key to press).
#+begin_src emacs-lisp
  (use-package which-key
    :ensure nil ;; Don't install which-key because it's now built-in
    :hook (after-init . which-key-mode)
    :diminish
    :custom
    (which-key-side-window-location 'bottom)
    (which-key-sort-order #'which-key-key-order-alpha) ;; Same as default, except single characters are sorted alphabetically
    (which-key-sort-uppercase-first nil)
    (which-key-add-column-padding 1) ;; Number of spaces to add to the left of each column
    (which-key-separator "  ")
    (which-key-min-display-lines 6)  ;; Increase the minimum lines to display because the default is only 1
    (which-key-idle-delay 0.5)       ;; Set the time delay (in seconds) for the which-key popup to appear
    (which-key-max-description-length 70)
    (which-key-allow-imprecise-window-fit nil)) ;; Fixes which-key window slipping out in Emacs Daemon
#+end_src

** Ws-butler
Removes whitespace from the ends of lines.
#+begin_src emacs-lisp
    (use-package ws-butler
      :hook (after-init . ws-butler-global-mode))
#+end_src

# FIXME: this is abit buggy atm, figure it out eventually
# ** Pdf-tools
# An emacs package for reading pdfs.

# #+begin_src emacs-lisp
# (use-package pdf-tools
#   :defer t
#   :commands (pdf-loader-install)
#   :mode "\\.pdf\\'"
#   :bind (:map pdf-view-mode-map
#               ("j" . pdf-view-next-line-or-next-page)
#               ("k" . pdf-view-previous-line-or-previous-page)
#               ("C-=" . pdf-view-enlarge)
#               ("C--" . pdf-view-shrink))
#   :init (pdf-loader-install)
#   :config (add-to-list 'revert-without-query ".pdf"))

# (add-hook 'pdf-view-mode-hook #'(lambda () (interactive) (display-line-numbers-mode -1)
#                                                          (blink-cursor-mode -1)
#                                                          (doom-modeline-mode -1)))
# #+end_src
