#!/usr/bin/env bash

# enforce strict mode
set -euo pipefail

# FIXME: when this check is activated, dunstc notification sounds fail
# if [[ "$#" -ne 0 ]]; then
#     echo " Usage:
#         This script plays a low notification sound.
#         Specifically meant to be used by dunstc(the notification daemon)
#         No arguments or flags are required
#
#         Run it like so:
#             $ $0
#         "
#     exit 1
# fi

pw-cat -p ~/.local/scripts/sounds/low.mp3
