#!/usr/bin/env bash

# strict mode
set -eou pipefail

# Current Theme
dir="$HOME/.config/rofi/powermenu/"
theme='style-2'

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostname`

# Options
shutdown='⏻ Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend='󰾊 Suspend'
logout=' Logout'
yes=' Yes'
no=' No'

# help message
usage(){
    echo " Usage:
        This script displays the power menu as a floating rofi window.
        The rofi window displayed will have the following options:
            - lock: locks the PC screen
            - suspend: suspends the PC screen
            - logout: logout the current user from the current session
            - reboot: restart the PC, killing current session
            - shutdown: turn off the PC gracefully

        "
}

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$host" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}

# Confirmation CMD
confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
	    if [[ $1 == '--lock' ]]; then
            xfce4-screensaver-command -l
		elif [[ $1 == '--suspend' ]]; then
			loginctl suspend
		elif [[ $1 == '--logout' ]]; then
			if [[ "$DESKTOP_SESSION" == 'qtile' ]]; then
				qtile cmd-obj -o cmd -f shutdown
			elif [[ "$DESKTOP_SESSION" == 'i3' ]]; then
				i3-msg exit
			fi
		elif [[ $1 == '--reboot' ]]; then
			loginctl reboot
		elif [[ $1 == '--shutdown' ]]; then
			loginctl poweroff
		fi
	else
	    usage
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
        run_cmd --lock
        ;;
    $suspend)
		run_cmd --suspend
        ;;
    $logout)
		run_cmd --logout
        ;;
esac
