#!/usr/bin/env bash

set -eo pipefail

output_dir="$HOME/Pictures/Screenshots/"
choice="$1"


usage() {
    echo " Usage:
        This script takes a system screesnhot using flameshot
        A notification is also sent using dunstc, showing if the screenshot
        was successful or not,

        To run it:
        $ $0 [selection] [fullscreen] [all]
        "
}

#ensure only 1 arg passed
if [[ "$#" -ne 1 ]]; then
    usage
    exit 1
else
    case "$choice" in
        selection)
            flameshot gui --path "$output_dir"
            ;;
        fullscreen)
            # takes full screenshot of where cursor is
            flameshot screen --delay 500 --path "$output_dir"
            ;;
        all)
            # takes screenshot of all screens
            flameshot full --delay 500 --path "$output_dir"
        ;;
        *)
            usage
            exit 1
        ;;
    esac
fi
