#!/usr/bin/env bash

set -eou pipefail

output_dir="$HOME/Pictures/Screenshots/"
choice="$1"

usage() {
    echo ""
    echo "Usage
    $ $0 [selection] [fullscreen] [all]
    "
}

#ensure only 1 arg passed
if [[ "$#" -ne 1 ]]; then
    usage
else
    case "$choice" in
        selection)
            flameshot gui --path "$output_dir"
            ;;
        fullscreen)
            # takes full screenshot of where cursor is
            flameshot screen --delay 500 --path "$output_dir"
            ;;
        all)
            # takes screenshot of all screens
            flameshot full --delay 500 --path "$output_dir"
        ;;
    esac
fi
