[general]
import = ["~/.config/alacritty/monokai.toml"]

[env]
# merges well with tmux
TERM = "xterm-256color"

[window]
# not very useful in a window manager
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 2
y = 2

[font]
size = 14

# NOTE: ensure youve installed the entire NerdFonts package
# that eliminates incorrect font fallback
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true

[bell]
animation = "Linear"
duration = 3
